apply plugin: 'java-library'

dependencies {
    implementation project(':modules:domain')
    implementation 'org.springframework:spring-context'
    api 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
}

test {
    useJUnitPlatform()
}
